# Welcome to Jekyll!
# This config file contains site-wide settings for your portfolio.

# Site settings
title: Portfolio
email: jsang542@gmail.com
description: >-
  SOC Analyst and Software Engineering student passionate about log analysis,
  security automation, and centralized authentication. This portfolio showcases
  projects, documentation, and technical achievements.

twitter_username: jsang542
github_username: KipkosgeiSang22
minimal_mistakes_skin: "neon"
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Africa/Nairobi

include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Author profile
author:
  name: "Joshua Sang"
  avatar: "/assets/images/linkedin.jpg"
  bio: "SOC intern and data analyst passionate about log analysis, security automation, and centralized authentication"
  location: "Nairobi, Kenya"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://kipkosgeisang22.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/KipkosgeiSang22"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"
    - label: "Phone"
      icon: "fas fa-fw fa-phone"
      url: "tel:+254742120301"

# Footer social links
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/jsang542"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/KipkosgeiSang22"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

# Layout defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Archives
category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
